// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imzubcykngpkpcnekzni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltenViY3lrbmdwa3BjbmVrem5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzMxMTUsImV4cCI6MjA2MDU0OTExNX0.eUqIHhR_w2WF0uGOXk13utG2oevjhEs4wxeSjL-jzW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);